FingertipsProfileManager/MainUI/Controllers/ContentController.cs
using Fpm.MainUI.Helpers;
using Fpm.MainUI.Models;
using Fpm.ProfileData;
using Fpm.ProfileData.Entities.Profile;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Routing;

namespace Fpm.MainUI.Controllers
{
    [RoutePrefix("content")]
    public class ContentController : Controller
    {
        private readonly IProfilesReader _reader;
        private readonly IProfilesWriter _writer;

        public ContentController(IProfilesReader reader, IProfilesWriter writer)
        {
            _reader = reader;
            _writer = writer;
        }

        [Route("content-index")]
        public ActionResult ContentIndex(int profileId = ProfileIds.Undefined)
        {
            var model = new ContentGridModel
            {
                SortBy = "Sequence",
                SortAscending = true,
                CurrentPageIndex = 1,
                PageSize = 100
            };

            model.ProfileList = ProfileMenuHelper.GetProfileListForCurrentUser();
            model.ProfileId = profileId;
            ViewBag.ProfileId = profileId;
            model.ContentItems = _reader.GetProfileContentItems(profileId)
                .OrderBy(x => x.Description).ToList();
            return View(model);
        }

        [Route("edit-content-item")]
        public ActionResult EditContentItem(string contentId, int profileId)
        {
            var contentItem = _reader.GetContentItem(Convert.ToInt32(contentId));
            ViewBag.ProfileId = profileId;
            ViewBag.ProfileName = _reader.GetProfileDetailsByProfileId(profileId).Name;
            return View("EditContentItem", contentItem);
        }

        [Route("create-content-item")]
        public ActionResult CreateContentItem(int selectedProfile)
        {
            var content = new ContentItem();
            content.ProfileId = selectedProfile;
            ViewBag.ProfileId = selectedProfile;
            return View(content);
        }

        [Route("insert-content-item")]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult InsertContentItem(ContentItem contentItem)
        {
            if (!TryUpdateModel(contentItem))
            {
                ViewBag.UpdateError = "Update Failure";
                return View("CreateContentItem", contentItem);
            }

            CleanContent(contentItem);

            // Check not duplicate content key
            var keyExist = _reader.GetContentItem(contentItem.ContentKey, contentItem.ProfileId);
            if (keyExist != null)
            {
                ViewBag.UpdateError = GetDuplicateContentKeyMessage(contentItem);
                ViewBag.ProfileId = contentItem.ProfileId;
                return View("CreateContentItem", contentItem);
            }

            // Save new content item
            var newContentItem = _writer.NewContentItem(contentItem.ProfileId,
                contentItem.ContentKey, contentItem.Description, contentItem.IsPlainText, contentItem.Content);
            AuditContentChange(newContentItem, "CREATED");

            return RedirectToAction("ContentIndex", new { profileId = contentItem.ProfileId });
        }

        [Route("update-content-item")]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult UpdateContentItem(ContentItem contentItem)
        {
            var newContentItem = new ContentItem();
            AutoMapper.Mapper.Map(contentItem, newContentItem);

            CleanContent(newContentItem);

            // Check not duplicate content key
            var existingContent = _reader.GetContentItem(contentItem.ContentKey, contentItem.ProfileId);
            if (existingContent != null && existingContent.Id != newContentItem.Id)
            {
                ViewBag.UpdateError = GetDuplicateContentKeyMessage(contentItem);
                ViewBag.ProfileName = contentItem.ProfileId;
                ViewBag.ProfileName = _reader.GetProfileDetailsByProfileId(contentItem.ProfileId).Name;

                return View("EditContentItem", contentItem);
            }

            _writer.UpdateContentItem(newContentItem);

            AuditContentChange(newContentItem, contentItem.Content);

            return RedirectToAction("ContentIndex", new { profileId = contentItem.ProfileId });
        }

        [Route("content-audit-list")]
        public ActionResult GetContentAuditList(IEnumerable<int> contentIds)
        {
            var contentAuditList = _reader.GetContentAuditList(contentIds.ToList());
            return PartialView("_ContentAudit", contentAuditList);
        }

        private static string GetDuplicateContentKeyMessage(ContentItem contentItem)
        {
            return string.Format("That content key '{0}' has already been used for this profile", contentItem.ContentKey);
        }

        [Route("delete-content-item")]
        public ActionResult DeleteContentItem(int contentItemId)
        {
            var contentItem = _writer.GetContentItem(contentItemId);

            if (contentItem == null)
            {
                throw new FpmException("Content item could not be deleted with id " + contentItemId);
            }

            _writer.DeleteContentItem(contentItem.ContentKey, contentItem.ProfileId);

            // Audit content item deletion
            var oldContent = contentItem.Content;
            contentItem.Content = "DELETED";
            AuditContentChange(contentItem, oldContent);

            return Json(new
            {
                Id = contentItemId,
                Message = "The content item was successfully deleted."
            });
        }

        [HttpPost]
        [Route("publish-content-item")]
        public async Task<ActionResult> PublishContentItem(IList<int> contentIds)
        {
            // Read the live update key from the configuration
            string liveUpdateKey = AppConfig.GetLiveUpdateKey();

            // Read the api url from the configuration
            string apiUrl = AppConfig.GetLiveSiteWsUrl();
            apiUrl = apiUrl + "api/contents";

            // Get the content item(s) to be published
            IList<ContentItem> contentItems = _reader.GetContentItems(contentIds);

            // Setup the http client object and post asynchronously to the web api method
            // to publish the document on live server
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // Serialise and add the live update key and content item(s) to the multi part form data content
                using (var formData = new MultipartFormDataContent())
                {
                    formData.Add(new StringContent(JsonConvert.SerializeObject(liveUpdateKey)), "LiveUpdateKey");

                    formData.Add(new StringContent(JsonConvert.SerializeObject(contentItems)), "content-items");

                    // Post asynchronously the request to the web api method
                    HttpResponseMessage response = await client.PostAsync(apiUrl, formData);

                    // If the publishing of the document succeeded then return a json result
                    if (response.IsSuccessStatusCode)
                    {
                        return new JsonResult
                        {
                            Data = "Success",
                            JsonRequestBehavior = JsonRequestBehavior.AllowGet
                        };
                    }
                }
            }

            throw new FpmException("Publishing live failed for the content(s)");
        }

        [Route("view-in-own-page")]
        public ActionResult ViewContentItemInOwnPage(int contentItemId)
        {
            var contentItem = _reader.GetContentItem(contentItemId);

            if (contentItem == null)
            {
                throw new FpmException("Content item could not be deleted with id " + contentItemId);
            }

            return View(contentItem);
        }

        private string formatPlainText(string content)
        {
            if (content == null)
            {
                return string.Empty;
            }

            //Persist any line breaks if plain text
            var replacedLineBreaksContent = Regex.Replace(content, "(<br />)", "\r\n");
            var removedHTMLContent = Regex.Replace(replacedLineBreaksContent, "<.*?>", string.Empty);
            return Regex.Replace(removedHTMLContent, "(\r\n|\n)", "<br />");
        }

        private void CleanContent(ContentItem contentItem)
        {
            var content = contentItem.IsPlainText ? formatPlainText(contentItem.Content) : contentItem.Content;
            if (content == null)
            {
                content = String.Empty;
            }

            contentItem.Content = content;

            // Ensure content key is always lower case
            contentItem.ContentKey = contentItem.ContentKey.ToLower();
        }

        private void AuditContentChange(ContentItem contentItem, string oldContent)
        {
            _writer.NewContentAudit(new ContentAudit
            {
                ContentKey = contentItem.ContentKey,
                ToContent = contentItem.Content,
                FromContent = oldContent,
                ContentId = contentItem.Id,
                UserName = UserDetails.CurrentUser().Name,
                Timestamp = DateTime.Now
            });
        }
    }
}

FingertipsProfileManager/MainUI/Views/Content/ContentIndex.cshtml
@using System.Web.Optimization
@using Fpm.MainUI
@using Fpm.MainUI.Helpers
@model Fpm.MainUI.Models.ContentGridModel
@{ Layout = "~/Views/Shared/_LayoutPage.cshtml"; }
@{
    ViewBag.Title = "FPM - Content Manager";
    var hasUserAccessToProfile = UserDetails.CurrentUser().HasWritePermissionsToProfile(Model.ProfileId);
    var isAdministrator = UserDetails.CurrentUser().IsAdministrator;
    var canPublishToLive = hasUserAccessToProfile || isAdministrator;
}
<link href="@(AppConfig.CssPath)TableSorter.css" rel="stylesheet" type="text/css" />
@Scripts.Render("~/content.js")

<div id="content-index" class="standardWidth">
    @using (Html.BeginForm("ContentIndex", "Content", FormMethod.Get, new { id = "IndicatorManagementForm" }))
    {
        <h2 class="subheading">Content in Fingertips</h2>

        // Profile drop down
        <div class="standardWidth">
            <b>Profile:</b>
            @Html.DropDownListFor(model => model.ProfileId, Model.ProfileList,
                new { @Id = "profileId", @Name = "profileId", @Class = "indicator-dropdown" })
            @Html.Hidden("sortBy", Model.SortBy)
            @Html.Hidden("ascending", Model.SortAscending)
            <input type="hidden" id="resetArea" name="resetArea" value="false" />
        </div>

        @Html.Partial("_ContentItemTable", Model.ContentItems)
    }

    <div id="content-index-button-box">
        @if (hasUserAccessToProfile)
        {
            <button type="button" class="btn btn-primary left" onclick="location.href = '@Url.Action("CreateContentItem", "Content", new {selectedProfile = Model.ProfileId})'" title="Click to add new content">
                New content
            </button>
        }
        
        @if (canPublishToLive)
        {
            <button type="button" class="btn btn-secondary right" id="publish_live" title="Select content item(s) and click to publish live">Publish to live site</button>
        }

        <button type="button" class="btn btn-secondary right" id="audit_history" title="Select content item(s) and click to view change history">Show history</button>
    </div>
</div>

<div class="a-modal">
    <!-- Place at bottom of page -->
</div>

FingertipsProfileManager/MainUI/Views/Content/CreateContentItem.cshtml
@using System.Web.Optimization
@using Fpm.MainUI
@using Fpm.MainUI.Helpers
@model Fpm.ProfileData.Entities.Profile.ContentItem
<link href="@(AppConfig.JsPath)tiny_mce/skins/lightgray/skin.min.css" rel="stylesheet" type="text/css" />
<script src="@(AppConfig.JsPath)tiny_mce/tinymce.min.js" type="text/javascript"></script>
<script src="@(AppConfig.JsPath)tiny_mce/jquery.tinymce.min.js" type="text/javascript"></script>
@Scripts.Render("~/content.js")

@{ Layout = "~/Views/Shared/_LayoutPage.cshtml"; }
@{
    ViewBag.Title = "FPM - Create Content";
}

@using (Html.BeginForm("InsertContentItem", "Content", FormMethod.Post, new { id = "SaveNewContent" }))
{
    <h2 class="subheading col-md-12">New Content</h2>
    @Html.Partial("_ContentErrorMessage")
    <div class="delete-indicators">
        <label class="content-item-detail-label">Content Key:</label>
        @Html.TextBoxFor(model => model.ContentKey, new {@class = "unselected-domain"})
        <span class="field-validation-valid" data-valmsg-for="ContentKey" data-valmsg-replace="true"></span>
    </div>

        @Html.Partial("_ContentDescription")
        @Html.Partial("_PlainTextCheckbox")
        @Html.Partial("_PlainTextWarning")
        @Html.Partial("_ContentTextArea")

        @Html.HiddenFor(x => x.Id)
        @Html.HiddenFor(x => x.ProfileId)

        <div class="row form-group">
            <div class="form-control-static col-lg-12">
                <input class="btn btn-primary" id="confirm" type="submit" value="Save" />
                @Html.Partial("_CancelButton", Model.ProfileId)
            </div>
        </div>

}

FingertipsProfileManager/MainUI/Views/Content/EditContentItem.cshtml
@using System.Web.Optimization
@using Fpm.MainUI
@using Fpm.MainUI.Helpers
@model Fpm.ProfileData.Entities.Profile.ContentItem
<link href="@(AppConfig.JsPath)tiny_mce/skins/lightgray/skin.min.css" rel="stylesheet" type="text/css" />

<script src="@(AppConfig.JsPath)tiny_mce/tinymce.min.js" type="text/javascript"></script>
<script src="@(AppConfig.JsPath)tiny_mce/jquery.tinymce.min.js" type="text/javascript"></script>
@Scripts.Render("~/content.js")

@{ Layout = "~/Views/Shared/_LayoutPage.cshtml"; }

@{
    var isUserAdmin = UserDetails.CurrentUser().IsAdministrator;
    var hasUserAccessToProfile = UserDetails.CurrentUser().HasWritePermissionsToProfile(Model.ProfileId);
}

@using (Html.BeginForm("UpdateContentItem", "Content", FormMethod.Post, new { id = "EditContent" }))
{
    <h2 class="subheading col-md-12">Edit content</h2>
    @Html.Partial("_ContentErrorMessage")
    <div class="row form-horizontal">
        <label class="col-lg-2 control-label">Profile:</label>
        <div class="col-lg-10 form-control-static">@ViewBag.ProfileName</div>
    </div>

        <div class="row form-group form-horizontal">
            <label class="col-lg-2 control-label">Content Key:</label>
            <div class="col-lg-10">
                @if (isUserAdmin)
                {
                    @Html.TextBoxFor(model => model.ContentKey, new { @class = "form-control" })
                    <span class="field-validation-valid" data-valmsg-for="ContentKey" data-valmsg-replace="true"></span>
                }
                else
                {
                    @Model.ContentKey
                }
            </div>
        </div>

        @Html.Partial("_ContentDescription")

        @* Plain text checkbox *@
if (Model.IsPlainText && isUserAdmin == false)
{
    <div class="row form-group form-horizontal">
        <label class="col-lg-2 control-label">Plain text:</label>
        <div class="col-lg-10">
            @Html.HiddenFor(x => x.IsPlainText)
            @Html.CheckBox("IsPlainText", Model.IsPlainText, new
       {
           value = Model.IsPlainText,
           disabled = "disabled",
           id = "disabledCheckBox",
           @class = "form-control"
       })
        </div>
    </div>
}
else
{
    @Html.Partial("_PlainTextCheckbox")
}
    @Html.Partial("_PlainTextWarning")
    @Html.Partial("_ContentTextArea")

    @Html.HiddenFor(x => x.ProfileId)
    @Html.HiddenFor(x => x.Id)
    @Html.HiddenFor(x => x.Description)
    @Html.HiddenFor(x => x.ContentKey)
    @Html.HiddenFor(x => x.Content, new { @Id = "oldContent", @Name = "oldContent" })

    <div class="row form-group">

        <div class="form-control-static col-lg-12">
            @if (hasUserAccessToProfile)
                {
                <input class="btn btn-primary" id="confirm" type="submit" value="Save" />
            }
            @Html.Partial("_CancelButton", Model.ProfileId)

            @if (hasUserAccessToProfile)
                {
                <input class="btn btn-danger" id="delete" type="button" value="Delete" />
            }
            else
            {
                <p class="warning">You do not have permission to save changes for "@ViewBag.ProfileName"</p>
            }
        </div>
    </div>

}

FingertipsProfileManager/MainUI/Views/Content/ViewContentItemInOwnPage.cshtml
@model Fpm.ProfileData.Entities.Profile.ContentItem
@{ Layout = "~/Views/Shared/_LayoutPage.cshtml"; }
@{
    ViewBag.Title = "FPM";
}
@(new MvcHtmlString(Model.Content))

FingertipsProfileManager/MainUI/Views/Content/_CancelButton.cshtml
@model int
<input class="btn btn-secondary" id="cancel" type="button"
       onclick="location.href = '@Url.Action("ContentIndex", new { profileId=Model })'"
       value="Cancel" />

FingertipsProfileManager/MainUI/Views/Content/_ContentAudit.cshtml
@using Fpm.MainUI
@model IEnumerable<Fpm.ProfileData.Entities.Profile.ContentAudit>
<script src="@(AppConfig.JsPath)common-functions.js" type="text/javascript"></script>
<div style="height: 500px; overflow: auto">
    <h3>
        Content Audit History
    </h3>
    <table class="sortable" style="width:auto">
        <thead>
            <tr>
                <th class="header">Date</th>
                <th class="header">Content Key</th>
                <th class="header">User</th>
                <th class="header">From</th>
                <th class="header">To</th>
            </tr>
        </thead>
        <tbody>
            @{
                int rowNumber = 0;
            }

            @foreach (var contentAudit in Model)
            {
                if (rowNumber % 2 == 0)
                {
                <tr class="odd">
                    <td>@contentAudit.Timestamp</td>
                    <td>@contentAudit.ContentKey</td>
                    <td>@contentAudit.UserName</td>
                    <td>@contentAudit.FromContent</td>
                    <td>@contentAudit.ToContent</td>
                </tr>
                }
                else
                {
                <tr class="even">
                    <td>@contentAudit.Timestamp</td>
                    <td>@contentAudit.ContentKey</td>
                    <td>@contentAudit.UserName</td>
                    <td>@contentAudit.FromContent</td>
                    <td>@contentAudit.ToContent</td>
                </tr>
                }
                rowNumber++;
            }
        </tbody>
    </table>
</div>

<p>
    <input class="small-button" id="Cancel" onclick="lightbox.hide()" value="Cancel" />
</p>

FingertipsProfileManager/MainUI/Views/Content/_ContentDescription.cshtml
@model Fpm.ProfileData.Entities.Profile.ContentItem
<div class="row form-group form-horizontal">
    <label class="col-lg-2 control-label">Description:</label>
    <div class="col-lg-10">
        @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
        <span class="field-validation-valid" data-valmsg-for="Description" data-valmsg-replace="true"></span>
    </div>
</div>

FingertipsProfileManager/MainUI/Views/Content/_ContentErrorMessage.cshtml
@if (ViewBag.UpdateError != null)
{
    <div style="width: 100%; padding-top: 100px;">
        <div class="alert alert-danger">
            <strong>@ViewBag.UpdateError</strong>
        </div>
    </div>
}

FingertipsProfileManager/MainUI/Views/Content/_ContentItemTable.cshtml
@using Fpm.MainUI.Helpers
@model IList<Fpm.ProfileData.Entities.Profile.ContentItem>

@{
    var isUserAdmin = UserDetails.CurrentUser().IsAdministrator;
}

@if (Model.Count > 0) {
<table class="grid sortable">
    <thead>
        <tr>
            @if (isUserAdmin)
            {
                <th class="header">ID</th>
            }
            <th class="header">Description</th>
            <th class="header">Content Key</th>
            <th>
                Select @Html.CheckBox("select-all", false, new { @class = "select-all-check-box" })
            </th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            @if (isUserAdmin)
            {
                <td class="left">
                    @item.Id
                </td>
            }
            <td class="left">
                @Html.ActionLink(item.Description, "EditContentItem",
                            new { contentId = item.Id, profileId = item.ProfileId }, null)
            </td>
            <td class="left">
                @item.ContentKey
            </td>
            <td class="center">
                @Html.CheckBox(item.Id + "_selected", false,
                                           new { @class = "indicator-check-box", @value = item.Id })
            </td>
        </tr>
    }
</table>
}
else
{
<label>No content items have been created for this profile.</label>
}

FingertipsProfileManager/MainUI/Views/Content/_ContentTextArea.cshtml
@model Fpm.ProfileData.Entities.Profile.ContentItem
    
<div id="html-editor">
    @Html.TextAreaFor(m => m.Content, new { @class = "tinymce", style = "width: 100%;" })
</div>

FingertipsProfileManager/MainUI/Views/Content/_PlainTextCheckbox.cshtml
@using Fpm.MainUI.Helpers
@model Fpm.ProfileData.Entities.Profile.ContentItem 

@{
    var isUserAdmin = UserDetails.CurrentUser().IsAdministrator;
    if (isUserAdmin)
    {
        <div class="delete-indicators">
            <label class="content-item-detail-label">Plain text:</label>
            @Html.CheckBoxFor(model => model.IsPlainText)
        </div>
    }
    else
    {
        @Html.HiddenFor(x => x.IsPlainText)
    }
}

FingertipsProfileManager/MainUI/Views/Content/_PlainTextWarning.cshtml
<p class="warning" id="ContentWarning" style="display: none;">
This content item is set to be plain text. Any HTML entered below will be converted to plain text when saved.
</p>