FingertipsProfileManager/MainUI/ViewModels/ProfileCollections/ProfileCollectionGridModel.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Fpm.ProfileData.Entities.Profile;

namespace Fpm.MainUI.ViewModels.ProfileCollections
{
    public class ProfileCollectionGridViewModel
    {
        public ProfileCollectionGridViewModel()
        {
            PageSize = 100;
            NumericPageCount = 15;
        }

        // Sorting-related properties
        public string SortBy { get; set; }
        public bool SortAscending { get; set; }

        // Paging-related properties
        public int CurrentPageIndex { get; set; }
        public int PageSize { get; set; }
        public int TotalRecordCount { get; set; }
        public int NumericPageCount { get; set; }

        // Filtering-related properties
        public int ProfileId { get; set; }
        public IEnumerable<SelectListItem> ProfileList { get; set; }
        public IList<ProfileCollection> ProfileCollectionGrid { get; set; }
    }
}

FingertipsProfileManager/MainUI/Controllers/ProfileCollectionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Fpm.MainUI.Helpers;
using Fpm.MainUI.ViewModels.ProfileCollections;
using Fpm.ProfileData;
using Fpm.ProfileData.Entities.Profile;
using Fpm.ProfileData.Repositories;

namespace Fpm.MainUI.Controllers
{
    [AdminUsersOnly]
    [RoutePrefix("profile-collections")]
    public class ProfileCollectionsController : Controller
    {
        private readonly IProfilesReader _reader;
        private readonly IProfileRepository _profileRepository;

        public ProfileCollectionsController(IProfilesReader reader, IProfileRepository profileRepository)
        {
            _reader = reader;
            _profileRepository = profileRepository;
        }

        [Route]
        public ActionResult ProfileCollectionsIndex()
        {
            var model = new ProfileCollectionGridViewModel
            {
                SortBy = "Sequence",
                SortAscending = true,
                CurrentPageIndex = 1,
                PageSize = 200
            };

            GetAllProfileCollections(model);

            return View(model);
        }

        [Route("edit-profile-collection")]
        public ActionResult EditProfileCollection(int profileCollectionId)
        {
            //Get all profiles
            IOrderedEnumerable<ProfileDetails> allProfiles = _reader.GetProfiles().OrderBy(x => x.Name);

            ProfileCollection profileCollection = _reader.GetProfileCollection(profileCollectionId);
            profileCollection.ProfileCollectionItems = new List<ProfileCollectionItem>();

            profileCollection.Id = profileCollectionId;
            IList<ProfileCollectionItem> profileCollectionItems = _reader.GetProfileCollectionItems(profileCollectionId);

            foreach (ProfileDetails profile in allProfiles)
            {
                profileCollection.ProfileCollectionItems.Add(new ProfileCollectionItem
                {
                    ProfileId = profile.Id,
                    profileDetails = profile,
                    Selected = profileCollectionItems.Any(x => x.ProfileId == profile.Id),
                    DisplayDomains =
                        profileCollectionItems.Where(x => x.ProfileId == profile.Id)
                            .Select(x => x.DisplayDomains)
                            .FirstOrDefault()
                });
            }

            if (HttpContext.Request.UrlReferrer != null)
                profileCollection.ReturnUrl = HttpContext.Request.UrlReferrer.ToString();

            return View("EditProfileCollection", profileCollection);
        }

        [Route("create-profile-collection")]
        public ActionResult CreateProfileCollection()
        {
            //Get all profiles
            IOrderedEnumerable<ProfileDetails> allProfiles = _reader.GetProfiles().OrderBy(x => x.Name);
            var profileCollection = new ProfileCollection { ProfileCollectionItems = new List<ProfileCollectionItem>() };

            foreach (ProfileDetails profileDetails in allProfiles)
            {
                profileCollection.ProfileCollectionItems.Add(new ProfileCollectionItem { profileDetails = profileDetails });
            }

            if (HttpContext.Request.UrlReferrer != null)
                profileCollection.ReturnUrl = HttpContext.Request.UrlReferrer.ToString();

            return View("CreateProfileCollection", profileCollection);
        }

        [Route("update-profile-collection")]
        public ActionResult UpdateProfileCollection(int id, string assignedProfiles,
            string collectionName, string collectionSkinTitle)
        {
            _profileRepository.UpdateProfileCollection(id, assignedProfiles,
               collectionName.Trim(), collectionSkinTitle.Trim());

            return RedirectToAction("ProfileCollectionsIndex");
        }

        [Route("insert-profile-collection")]
        public ActionResult InsertProfileCollection(ProfileCollection profileCollection, string assignedProfiles)
        {
            var newProfileCollection = new ProfileCollection
            {
                CollectionName = profileCollection.CollectionName,
                CollectionSkinTitle = profileCollection.CollectionSkinTitle
            };

            _profileRepository.CreateProfileCollection(newProfileCollection, assignedProfiles);

            return RedirectToAction("ProfileCollectionsIndex");
        }

        private void GetAllProfileCollections(ProfileCollectionGridViewModel viewModel)
        {
            viewModel.ProfileCollectionGrid = _reader.GetProfileCollections().OrderBy(x => x.CollectionName).ToList();
        }
    }
}

FingertipsProfileManager/MainUI/Views/ProfileCollections/CreateProfileCollection.cshtml
@model Fpm.ProfileData.Entities.Profile.ProfileCollection
@{ Layout = "~/Views/Shared/_LayoutPage.cshtml"; }
@{
    ViewBag.Title = "FPM - Create Profile Collection";
}
@Html.Partial("_ProfileCollectionIncludes")

<div class="standardWidth">

    <div class="row col-md-12">
        <h2 class="subheading">New profile collection</h2>
    </div>

    @using (Html.BeginForm("InsertProfileCollection", "ProfileCollections", FormMethod.Post, new { id = "CreateProfileCollection" }))
    {
        @Html.HiddenFor(x => x.Id)
        @Html.Hidden("assignedProfiles", new { id = "assignedProfiles", name = "assignedProfiles" })

        @Html.Partial("_ProfileCollectionDetails")

        <div class="row col-md-12">
            <input class="btn btn-primary" id="create_profile_collection" type="button" value="Save" />
            <input class="btn btn-secondary" id="cancel_profile" type="button" onclick="location.href = '@Model.ReturnUrl'" value="Cancel" />
        </div>

        <table class="grid sortable">
            <thead>
                <tr>
                    <th>Collection Name</th>
                    <th>Select</th>
                </tr>
            </thead>
            @foreach (var profile in Model.ProfileCollectionItems)
            {
                <tr>
                    <td class="left">
                        @profile.profileDetails.Name
                    </td>
                    <td class="center">@Html.CheckBox(profile.profileDetails.Name + "_assigned", false, new { @class = "selectable-check-box", @value = profile.profileDetails.Id })
                    </td>
                </tr>
            }
        </table>
    }
</div>

FingertipsProfileManager/MainUI/Views/ProfileCollections/EditProfileCollection.cshtml
@model Fpm.ProfileData.Entities.Profile.ProfileCollection
@{ Layout = "~/Views/Shared/_LayoutPage.cshtml"; }
@{
    ViewBag.Title = "FPM - Edit Profile Collection";
}
@Html.Partial("_ProfileCollectionIncludes")

<div class="standardWidth container">

    <div class="row col-md-12">
        <h2 class="subheading">Edit profile collection</h2>
    </div>

    @using (Html.BeginForm("UpdateProfileCollection", "ProfileCollections", FormMethod.Post, new {id = "UpdateProfileCollection"}))
    {
        @Html.HiddenFor(x => x.Id)
        @Html.HiddenFor(x => x.ReturnUrl)
        @Html.Hidden("assignedProfiles", new {id = "assignedProfiles", name = "assignedProfiles"})

        @Html.Partial("_ProfileCollectionDetails")

        <div class="row col-md-12">
            <input class="btn btn-primary" id="update_profile_collection" type="button" value="Save"/>
            <input class="btn btn-secondary" id="cancel_profile" type="button" onclick="location.href = '@Model.ReturnUrl'" value="Cancel"/>
        </div>

        <div class="row">
            <div class="col-md-8 text-right">
                <input id="toggle-unchecked-display" class="btn btn-primary" type="button" value="Show/hide included"/>
            </div>
            <div class="col-md-8">
                <table class="grid sortable">
                    <thead>
                    <tr>
                        <th>Profile</th>
                        <th>Select</th>
                        <th>Display Domains?</th>
                    </tr>
                    </thead>
                    @foreach (var profile in Model.ProfileCollectionItems)
                    {
                        <tr>
                            <td class="left">
                                @Html.ActionLink(profile.profileDetails.Name, "EditProfile", "Profile", new {profileKey = profile.profileDetails.UrlKey}, new {})
                            </td>
                            <td class="center">
                                @Html.CheckBox(profile.ProfileId + "_assigned", profile.Selected,
                                    new {@class = "selectable-check-box", @value = profile.ProfileId})
                            </td>
                            <td class="center">
                                @Html.CheckBox(profile.ProfileId + "_display_domains", profile.DisplayDomains,
                                    new {id = profile.ProfileId + "_display_domains", @class = "display-domains-check-box", @value = profile.DisplayDomains})
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    }
</div>

FingertipsProfileManager/MainUI/Views/ProfileCollections/ProfileCollectionsIndex.cshtml
@using System.Web.Mvc.Html
@model Fpm.MainUI.ViewModels.ProfileCollections.ProfileCollectionGridViewModel
@{ Layout = "~/Views/Shared/_LayoutPage.cshtml"; }
@{
    ViewBag.Title = "FPM - Profile Collection Manager";
}
@Html.Partial("_ProfileCollectionIncludes")

<div class="standardWidth">

    <div class="row col-md-12">
        <h2 class="subheading">Profile collections</h2>

        @if (Model.ProfileCollectionGrid.Count > 0)
        {
            <table class="grid sortable">
                <thead>
                    <tr>
                        <th class="header">Collection Id</th>
                        <th class="header">Collection Name</th>
                        <th class="header">Collection Title</th>
                    </tr>
                </thead>
                @foreach (var item in Model.ProfileCollectionGrid)
                {
                    <tr>
                        <td class="left">
                            @item.Id.ToString()
                        </td>
                        <td class="left">
                            @Html.ActionLink(item.CollectionName, "EditProfileCollection", 
                                new { profileCollectionId = item.Id, profileCollectionName = item.CollectionName }, null)
                        </td>
                        <td class="left">
                            @item.CollectionSkinTitle
                        </td>
                    </tr>
                }
            </table>
        }
        else
        {
            <label>No profiles items have been added to this profile collection.</label>
        }

        <input type="button" value="New profile collection" class="btn btn-primary" 
               onclick="location.href = '@Url.Action("CreateProfileCollection", "ProfileCollections")'" />
    </div>
</div>

FingertipsProfileManager/MainUI/Views/ProfileCollections/_ProfileCollectionDetails.cshtml
@model Fpm.ProfileData.Entities.Profile.ProfileCollection

<div class="row col-md-12">
    <label class="content-item-detail-label">Collection Name:</label>
    @Html.TextBoxFor(model => model.CollectionName, new { @class = "unselected-domain" })
    <span class="field-validation-valid" data-valmsg-for="CollectionName" data-valmsg-replace="true"></span>
</div>

<div class="row col-md-12">
    <label class="content-item-detail-label">Collection Title:</label>
    @Html.TextBoxFor(model => model.CollectionSkinTitle, new { @class = "unselected-domain" })
    <span class="field-validation-valid" data-valmsg-for="CollectionSkinTitle" data-valmsg-replace="true"></span>
</div>

FingertipsProfileManager/MainUI/Views/ProfileCollections/_ProfileCollectionIncludes.cshtml
@using Fpm.MainUI
<script src="@(AppConfig.JsPath)ProfileCollections/profile-collections.js" type="text/javascript"></script>
<link href="@(AppConfig.CssPath)TableSorter.css" rel="stylesheet" type="text/css" />