FingertipsProfileManager/MainUI/ViewModels/ExceptionLog/ExceptionIndexViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;

namespace Fpm.MainUI.ViewModels.ExceptionLog
{
    public class ExceptionIndexViewModel
    {
        public IList<ProfileData.Entities.Exceptions.ExceptionLog> ExceptionList { get; set; }
        public IEnumerable<SelectListItem> ServerList { get; set; }
        public string Server { get; set; }
        public bool LiveServersFilterApplied { get; set; }
        public bool ApiErrorsFilterApplied { get; set; }
        public int NumberOfDays { get; set; }
    }
}

FingertipsProfileManager/MainUI/Controllers/ExceptionLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Fpm.MainUI.Helpers;
using Fpm.MainUI.ViewModels.ExceptionLog;
using Fpm.ProfileData;
using Fpm.ProfileData.Entities.Exceptions;
using Fpm.ProfileData.Repositories;

namespace Fpm.MainUI.Controllers
{
    [RoutePrefix("exceptions")]
    public class ExceptionLogController : Controller
    {
        private readonly IExceptionsRepository _exceptionLogRepository;

        public ExceptionLogController(IExceptionsRepository exceptionLogRepository)
        {
            _exceptionLogRepository = exceptionLogRepository;
        }

        [HttpGet]
        [Route]
        public ActionResult ExceptionIndex()
        {
            var viewModel = new ExceptionIndexViewModel()
            {
                ServerList = CommonUtilities.GetDistinctExceptionServers(),
                ExceptionList = GetExceptions(0, new string[] { ExceptionOptions.AllServers }),
                Server = ExceptionOptions.AllServers,
                LiveServersFilterApplied = false,
                ApiErrorsFilterApplied = false,
                NumberOfDays = 0
            };

            return View(viewModel);
        }

        [HttpPost]
        [Route("filtered-exceptions")]
        public ActionResult FilteredExceptions(ExceptionIndexViewModel viewModel)
        {
            IList<ExceptionLog> exceptionList;

            if (viewModel.LiveServersFilterApplied)
            {
                viewModel.ServerList = CommonUtilities.GetLiveExceptionServers();
                
                if (viewModel.Server == ExceptionOptions.AllServers)
                {
                    var servers = new[] { ServerNames.Live1, ServerNames.Live2 };
                    exceptionList = GetExceptions(viewModel.NumberOfDays, servers);
                }
                else
                {
                    exceptionList = GetExceptions(viewModel.NumberOfDays, new string[] { viewModel.Server });
                }
            }
            else
            {
                viewModel.ServerList = CommonUtilities.GetDistinctExceptionServers();

                exceptionList = GetExceptions(viewModel.NumberOfDays, new string[] { viewModel.Server });
            }

            if (viewModel.ApiErrorsFilterApplied)
            {
                exceptionList = exceptionList.Where(x => x.Url.Contains("api/")).ToList();
            }

            viewModel.ExceptionList = exceptionList;

            return View("ExceptionIndex", viewModel);
        }

        [Route("exception/{id}")]
        public ActionResult ExceptionDetails(int id)
        {
            var exception = _exceptionLogRepository.GetException(id);
            return View(exception);
        }

        [Route("exception-partial/{id}")]
        public ActionResult ShowExceptionDetails(string id)
        {
            var exception = _exceptionLogRepository.GetException(Convert.ToInt32(id));
            return PartialView("_ExceptionDetail", exception);
        }

        private IList<ExceptionLog> GetExceptions(int exceptionDays, string[] exceptionServer)
        {
            if (exceptionServer == null)
            {
                exceptionServer = new string[] {Environment.MachineName};
            }

            return exceptionServer[0] == ExceptionOptions.AllServers
                ? _exceptionLogRepository.GetExceptionsForAllServers(exceptionDays)
                : _exceptionLogRepository.GetExceptionsForSpecificServers(exceptionDays, exceptionServer);
        }
    }
}

FingertipsProfileManager/MainUI/Views/ExceptionLog/ExceptionDetails.cshtml
@using System.Web.Optimization
@model Fpm.ProfileData.Entities.Exceptions.ExceptionLog
@{ Layout = "~/Views/Shared/_LayoutPage.cshtml"; }
@{
    ViewBag.Title = "FPM - Exception Details";
}
@Scripts.Render("~/exception-log.js")

<div class="standardWidth">
    @Html.Partial("_ExceptionDetail")
</div>

<script type="text/javascript">
     $('#exception-detail').show();
     $('#exception-detail-buttons').hide();
</script>

FingertipsProfileManager/MainUI/Views/ExceptionLog/ExceptionIndex.cshtml
@using System.Web.Mvc.Html
@using System.Web.Optimization
@using Fpm.MainUI
@using Fpm.MainUI.Helpers
@model Fpm.MainUI.ViewModels.ExceptionLog.ExceptionIndexViewModel
@{ Layout = "~/Views/Shared/_LayoutPage.cshtml"; }
@{
    ViewBag.Title = "FPM - Exception Log";

    var liveServersButtonStyle = "btn btn-secondary";
    var apiErrorsButtonStyle = "btn btn-secondary";

    if (Model.LiveServersFilterApplied)
    {
        liveServersButtonStyle = "btn btn-primary";
    }

    if (Model.ApiErrorsFilterApplied)
    {
        apiErrorsButtonStyle = "btn btn-primary";
    }
}
<link href="@(AppConfig.CssPath)TableSorter.css" rel="stylesheet" type="text/css" />
@Scripts.Render("~/exception-log.js")

<div class="container">
    <h2 class="subheading">Exception log</h2>

    <div class="row">
        @using (Html.BeginForm("FilteredExceptions", "ExceptionLog", FormMethod.Post, new {id = "reload-exceptions-form" }))
        {
        <div class="col-md-4">
            <b>Days:</b>
            @Html.DropDownListFor(x => x.NumberOfDays, new SelectList(CommonUtilities.GetExceptionDays(), "Text", "Value", "0"),
                new { @class = "indicator-dropdown", onchange = "triggerNumberOfDaysChangedEvent(this)" })
            <b>Server:</b>
            @Html.DropDownListFor(x => x.ServerList, new SelectList(Model.ServerList, "Text", "Value", Server.MachineName),
                new { @class = "indicator-dropdown", onchange = "triggerServerListChangedEvent(this)" })
        </div>

            @Html.HiddenFor(x => x.LiveServersFilterApplied)
            @Html.HiddenFor(x => x.ApiErrorsFilterApplied)
            @Html.HiddenFor(x => x.Server)

            <div class="col-md-2">
                <b>@Model.ExceptionList.Count</b> exceptions
            </div>

            <div class="col-md-4">
                <b>Filters:</b>
                <input id="live-servers" type="button" value="Live servers" class="@liveServersButtonStyle" />
                <input id="api-errors" type="button" value="API errors" class="@apiErrorsButtonStyle"/>
            </div>
        }
    </div>
    


    <table class="grid sortable">
        <thead>
        <tr>
            <th class="header">Date</th>
            <th class="header">Server</th>
            <th class="header">Message</th>
            <th class="header">Type</th>
            <th class="header">URL</th>
            <th class="header">Username</th>
        </tr>
        </thead>

        @foreach (var item in Model.ExceptionList)
        {
            <tr>
                <td class="left">
                    <a class="exception-detail-link show-spinner" id="@item.Id.ToString()" href="#">@item.Date.ToShortDateString()</a>
                    <br>@item.Date.ToShortTimeString()
                </td>
                <td class="left">
                    @item.Server
                    <br>@item.Application
                </td>
                <td class="left">
                    @item.Message
                </td>
                <td class="left">
                    @item.Type
                </td>
                <td class="left">
                    <a href="@item.Url" target="_blank">@item.Url</a>
                </td>
                <td class="left">
                    @item.UserName
                </td>
            </tr>
        }
    </table>
</div>

FingertipsProfileManager/MainUI/Views/ExceptionLog/_ExceptionDetail.cshtml
@model Fpm.ProfileData.Entities.Exceptions.ExceptionLog

<div id="exception-detail" style="display none;">
    <h2>Exception Detail</h2>
    <div>
        <label class="exception-detail-label">Message</label><div class="exception-detail">@Model.Message</div>
    </div>
    <div>
        <label class="exception-detail-label">URL</label><a href="@Model.Url" target="_blank">@Model.Url</a>
    </div>
    <div>
        <label class="exception-detail-label">Application</label><span class="exception-detail">@Model.Application</span>
    </div>
    <div>
        <label class="exception-detail-label">Type</label><div class="exception-detail">@Model.Type</div>
    </div>
    <div>
        <label class="exception-detail-label">Stack Trace</label><div class="exception-detail">@Model.StackTrace</div>
    </div>
    <div>
        <label class="exception-detail-label">Server</label><span class="exception-detail">@Model.Server</span>
    </div>
    <div>
        <label class="exception-detail-label">Id</label><span class="exception-detail">@Model.Id</span>
    </div>
    <div>
        <label class="exception-detail-label">Date</label><span class="exception-detail">@Model.Date.ToShortDateString() @Model.Date.ToShortTimeString()</span>
    </div>
    <div>
        <label class="exception-detail-label">Username</label><div class="exception-detail">@Model.UserName</div>
    </div>
</div>

<p id="exception-detail-buttons">
    <input class="small-button" id="Close" onclick="lightbox.hide()" value="Close" />
    <a href="/exceptions/exception/@Model.Id" target="_blank">View full screen in new window</a>
</p>